import { AnalysisResult, StructuredReport, MatchedInsight } from './types';

/**
 * Professional export utilities for Grok Genome.
 * These produce clean, machine- and human-readable outputs suitable for
 * further analysis in other tools (R, Python, Excel, research databases, LLMs, etc.).
 * All functions are pure and client-side.
 */

const DISCLAIMER = "This report is for educational and research purposes only. It does not constitute medical advice. Genetic associations are probabilistic and context-dependent. Always consult a qualified healthcare professional or genetic counselor. All analysis performed locally in your browser using the Grok Genome knowledge base.";

export function toStructuredReport(result: AnalysisResult): StructuredReport {
  const highActionability = result.insights.filter(i => 
    i.snp.clinicalActionability === 'high' || i.snp.clinicalActionability === 'consult_specialist'
  ).length;

  const increasedRisk = result.insights.filter(i => 
    i.interpretation.effect === 'increased_risk' || i.interpretation.effect === 'affected'
  ).length;

  const carriers = result.insights.filter(i => 
    i.interpretation.effect === 'carrier'
  ).length;

  return {
    meta: {
      generatedAt: result.generatedAt,
      fileName: result.fileName,
      format: result.format,
      totalVariantsParsed: result.totalVariantsParsed,
      matchedVariants: result.matchedVariants,
      knowledgeBaseVersion: result.knowledgeBaseVersion,
      disclaimer: DISCLAIMER
    },
    summary: {
      highActionabilityCount: highActionability,
      increasedRiskCount: increasedRisk,
      carrierFindings: carriers
    },
    categories: result.categories,
    allInsights: result.insights
  };
}

export function toJSON(result: AnalysisResult): string {
  const report = toStructuredReport(result);
  return JSON.stringify(report, null, 2);
}

export function toCSV(result: AnalysisResult, delimiter = ','): string {
  const headers = [
    'rsid', 'gene', 'trait', 'category', 'genotype', 'effect', 'description', 
    'impact', 'confidence', 'evidenceLevel', 'clinicalActionability', 'source', 'notes'
  ];

  const rows = result.insights.map((insight: MatchedInsight) => {
    const { snp, genotype, interpretation } = insight;
    return [
      snp.rsid,
      snp.gene,
      `"${snp.trait.replace(/"/g, '""')}"`,
      snp.category,
      genotype,
      interpretation.effect,
      `"${interpretation.description.replace(/"/g, '""')}"`,
      interpretation.impact,
      interpretation.confidence,
      snp.evidenceLevel || '',
      snp.clinicalActionability || '',
      snp.source,
      snp.notes ? `"${snp.notes.replace(/"/g, '""')}"` : ''
    ].join(delimiter);
  });

  return [headers.join(delimiter), ...rows].join('\n');
}

export function toTSV(result: AnalysisResult): string {
  return toCSV(result, '\t');
}

export function toMarkdown(result: AnalysisResult): string {
  const report = toStructuredReport(result);
  let md = `# Grok Genome Analysis Report\n\n`;
  md += `**File:** ${report.meta.fileName}  |  **Generated:** ${new Date(report.meta.generatedAt).toLocaleString()}  |  **KB Version:** ${report.meta.knowledgeBaseVersion}\n\n`;
  md += `> ${DISCLAIMER}\n\n`;

  md += `## Summary\n\n`;
  md += `- High actionability findings: **${report.summary.highActionabilityCount}**\n`;
  md += `- Increased risk / affected: **${report.summary.increasedRiskCount}**\n`;
  md += `- Carrier status findings: **${report.summary.carrierFindings}**\n`;
  md += `- Variants analyzed: ${report.meta.matchedVariants} / ${report.meta.totalVariantsParsed}\n\n`;

  Object.entries(report.categories).forEach(([cat, insights]) => {
    if (!insights || insights.length === 0) return;
    md += `## ${cat.replace('_', ' ').toUpperCase()}\n\n`;
    insights.forEach(i => {
      md += `### ${i.snp.gene} (${i.snp.rsid}) — ${i.genotype}\n`;
      md += `${i.interpretation.description}\n\n`;
      md += `- **Effect:** ${i.interpretation.effect} | **Impact:** ${i.interpretation.impact} | **Evidence:** ${i.snp.evidenceLevel}\n`;
      if (i.snp.references?.length) md += `- References: ${i.snp.references.join(', ')}\n`;
      if (i.snp.notes) md += `- Notes: ${i.snp.notes}\n`;
      md += `\n`;
    });
  });

  md += `---\n\n*Generated by Grok Genome — 100% client-side*\n`;
  return md;
}

// Helper for future richer PDF data (used by pdfExport.ts)
export function prepareRichPDFData(result: AnalysisResult) {
  return {
    ...toStructuredReport(result),
    generatedAtFormatted: new Date(result.generatedAt).toLocaleDateString(),
  };
}
