import { SNPInfo } from './types';

export const KNOWLEDGE_BASE: SNPInfo[] = [
  // APOE
  { rsid: "rs429358", gene: "APOE", trait: "Alzheimer's Disease Risk & Lipid Metabolism", category: "disease_risk", genotypes: { "CC": { effect: "increased_risk", description: "APOE4 allele. Significantly higher lifetime risk of late-onset Alzheimer's (3-15x depending on copy number). Also associated with higher LDL cholesterol.", impact: "High impact", confidence: "high" }, "CT": { effect: "increased_risk", description: "One APOE4 allele (E3/E4). Moderately elevated Alzheimer's risk (~2-3x). Monitor cardiovascular health.", impact: "Moderate-high", confidence: "high" }, "TT": { effect: "neutral", description: "No APOE4 alleles. Average population risk.", impact: "Baseline", confidence: "high" } }, source: "ClinVar / GWAS" },
  { rsid: "rs7412", gene: "APOE", trait: "APOE2 Allele Effects", category: "disease_risk", genotypes: { "CC": { effect: "neutral", description: "Standard profile.", impact: "", confidence: "high" }, "CT": { effect: "protective", description: "One APOE2. Often lower LDL and possible longevity association.", impact: "Mild protective for CVD", confidence: "high" }, "TT": { effect: "protective", description: "Rare APOE2/2. Lower Alzheimer's risk but monitor lipids.", impact: "Complex", confidence: "high" } }, source: "ClinVar" },

  // Lactose
  { rsid: "rs4988235", gene: "LCT", trait: "Lactose Persistence", category: "nutrition", genotypes: { "AA": { effect: "neutral", description: "Lactase persistence. Likely digests lactose well into adulthood.", impact: "Tolerant", confidence: "high" }, "AG": { effect: "neutral", description: "Likely tolerant.", impact: "", confidence: "high" }, "GG": { effect: "increased_risk", description: "Lactase non-persistence genotype. Higher probability of adult lactose intolerance symptoms.", impact: "Common intolerance signal", confidence: "high" } }, source: "GWAS" },

  // Caffeine
  { rsid: "rs762551", gene: "CYP1A2", trait: "Caffeine Metabolism", category: "nutrition", genotypes: { "AA": { effect: "neutral", description: "Fast metabolizer. Caffeine clears quickly.", impact: "", confidence: "high" }, "AC": { effect: "neutral", description: "Intermediate.", impact: "", confidence: "high" }, "CC": { effect: "increased_risk", description: "Slow metabolizer. Caffeine lingers. Evening consumption may disrupt sleep more.", impact: "Slow clearance", confidence: "high" } }, source: "Caffeine GWAS" },

  // MTHFR
  { rsid: "rs1801133", gene: "MTHFR", trait: "Folate Metabolism (C677T)", category: "nutrition", genotypes: { "AA": { effect: "neutral", description: "Normal activity.", impact: "", confidence: "high" }, "AG": { effect: "neutral", description: "Mildly reduced activity.", impact: "", confidence: "high" }, "GG": { effect: "decreased_risk", description: "Reduced MTHFR efficiency. Many people benefit from methylated folate supplements.", impact: "Consider methylated B9", confidence: "high" } }, source: "PharmGKB" },

  // Pharmacogenomics
  { rsid: "rs9923231", gene: "VKORC1", trait: "Warfarin Dose Sensitivity", category: "pharmacogenomics", genotypes: { "AA": { effect: "responder", description: "High sensitivity. Typically needs much lower warfarin dose.", impact: "Clinical actionability high", confidence: "high" }, "AG": { effect: "responder", description: "Intermediate sensitivity.", impact: "Dose adjustment often needed", confidence: "high" }, "GG": { effect: "neutral", description: "Lower sensitivity.", impact: "", confidence: "high" } }, source: "CPIC" },
  { rsid: "rs4244285", gene: "CYP2C19", trait: "Clopidogrel Activation", category: "pharmacogenomics", genotypes: { "AA": { effect: "non_responder", description: "Poor metabolizer. Reduced antiplatelet effect. Consider alternatives.", impact: "High", confidence: "high" }, "AG": { effect: "responder", description: "Intermediate.", impact: "", confidence: "high" }, "GG": { effect: "neutral", description: "Normal metabolizer.", impact: "", confidence: "high" } }, source: "CPIC/FDA" },

  // ACTN3 + FTO + TCF7L2
  { rsid: "rs1815739", gene: "ACTN3", trait: "Muscle Fiber Type & Athletic Tendency", category: "fitness", genotypes: { "CC": { effect: "neutral", description: "RR. Tendency toward fast-twitch fibers — power, sprint, strength sports.", impact: "Power profile", confidence: "moderate" }, "CT": { effect: "neutral", description: "RX. Balanced.", impact: "", confidence: "moderate" }, "TT": { effect: "neutral", description: "XX. Higher slow-twitch fibers. Endurance orientation.", impact: "Endurance lean", confidence: "moderate" } }, source: "Athletic GWAS" },
  { rsid: "rs9939609", gene: "FTO", trait: "Appetite & Body Weight Tendency", category: "nutrition", genotypes: { "AA": { effect: "increased_risk", description: "Associated with increased appetite and higher obesity risk in many populations.", impact: "Strongest risk allele", confidence: "high" }, "AT": { effect: "neutral", description: "Intermediate.", impact: "", confidence: "high" }, "TT": { effect: "protective", description: "Lower risk allele.", impact: "Favorable", confidence: "high" } }, source: "Obesity GWAS" },
  { rsid: "rs7903146", gene: "TCF7L2", trait: "Type 2 Diabetes Risk", category: "disease_risk", genotypes: { "CC": { effect: "protective", description: "Lower risk allele.", impact: "Favorable", confidence: "high" }, "CT": { effect: "neutral", description: "Average risk.", impact: "", confidence: "high" }, "TT": { effect: "increased_risk", description: "One of the strongest common genetic signals for T2D risk.", impact: "Significant", confidence: "high" } }, source: "Diabetes genetics" },

  // More high-value
  { rsid: "rs10455872", gene: "LPA", trait: "Lipoprotein(a) Cardiovascular Risk", category: "disease_risk", genotypes: { "AA": { effect: "increased_risk", description: "Elevated Lp(a). Important independent cardiovascular risk marker.", impact: "High", confidence: "high" }, "AG": { effect: "neutral", description: "Intermediate.", impact: "", confidence: "high" }, "GG": { effect: "protective", description: "Lower Lp(a). Favorable.", impact: "", confidence: "high" } }, source: "Large GWAS" },
  { rsid: "rs4680", gene: "COMT", trait: "Dopamine Regulation (Warrior / Worrier)", category: "wellness", genotypes: { "AA": { effect: "neutral", description: "Met/Met. Higher prefrontal dopamine. May feel stress more but excel at focus tasks.", impact: "Worrier profile", confidence: "moderate" }, "AG": { effect: "neutral", description: "Balanced.", impact: "", confidence: "moderate" }, "GG": { effect: "neutral", description: "Val/Val. Faster dopamine breakdown. Often resilient under stress.", impact: "Warrior profile", confidence: "moderate" } }, source: "COMT literature" },
  { rsid: "rs1799971", gene: "OPRM1", trait: "Opioid & Reward Sensitivity", category: "pharmacogenomics", genotypes: { "AA": { effect: "neutral", description: "Normal mu-opioid receptor.", impact: "", confidence: "moderate" }, "AG": { effect: "responder", description: "G carriers often report stronger opioid and alcohol effects.", impact: "Higher sensitivity", confidence: "moderate" }, "GG": { effect: "responder", description: "Stronger response reported.", impact: "", confidence: "moderate" } }, source: "Pain genetics" },

  // Carrier-relevant & additional
  { rsid: "rs1800562", gene: "HFE", trait: "Hereditary Hemochromatosis Risk (C282Y)", category: "disease_risk", genotypes: { "AA": { effect: "affected", description: "Two C282Y mutations. High risk of iron overload. Worth clinical iron studies discussion.", impact: "High actionability", confidence: "high" }, "AG": { effect: "carrier", description: "Carrier (C282Y heterozygote). Usually low risk but monitor if symptoms.", impact: "Carrier", confidence: "high" }, "GG": { effect: "neutral", description: "No C282Y mutation.", impact: "", confidence: "high" } }, source: "ClinVar" },
  { rsid: "rs6025", gene: "F5", trait: "Factor V Leiden Thrombophilia", category: "disease_risk", genotypes: { "AA": { effect: "affected", description: "Homozygous Factor V Leiden. Significantly increased clotting risk.", impact: "High", confidence: "high" }, "AG": { effect: "carrier", description: "Heterozygous. Moderately increased venous thrombosis risk.", impact: "Carrier", confidence: "high" }, "GG": { effect: "neutral", description: "Wild type. Normal risk.", impact: "", confidence: "high" } }, source: "ClinVar" },

  // A few more for demo richness
  { rsid: "rs53576", gene: "OXTR", trait: "Social Cognition Tendencies", category: "wellness", genotypes: { "AA": { effect: "neutral", description: "AA genotype often discussed in context of social bonding differences.", impact: "Exploratory", confidence: "emerging" }, "AG": { effect: "neutral", description: "", impact: "", confidence: "emerging" }, "GG": { effect: "neutral", description: "GG sometimes reported as more 'socially responsive' (evidence mixed).", impact: "", confidence: "emerging" } }, source: "Candidate gene studies" },
  { rsid: "rs1801131", gene: "MTHFR", trait: "MTHFR A1298C", category: "nutrition", genotypes: { "AA": { effect: "neutral", description: "Normal.", impact: "", confidence: "high" }, "AC": { effect: "neutral", description: "Mild effect alone.", impact: "", confidence: "high" }, "CC": { effect: "neutral", description: "Reduced activity, especially with 677T.", impact: "", confidence: "high" } }, source: "MTHFR" }
];

export const CATEGORY_LABELS: Record<string, { label: string; icon: string; color: string }> = {
  disease_risk: { label: "Disease Predispositions", icon: "Heart", color: "#ef4444" },
  carrier: { label: "Carrier Status", icon: "Users", color: "#f59e0b" },
  pharmacogenomics: { label: "Drug Response", icon: "Zap", color: "#3b82f6" },
  nutrition: { label: "Nutrition & Metabolism", icon: "Heart", color: "#10b981" },
  fitness: { label: "Fitness & Performance", icon: "Activity", color: "#8b5cf6" },
  wellness: { label: "Wellness & Behavior", icon: "BookOpen", color: "#06b6d4" },
};
export const CATEGORY_ORDER = ['disease_risk', 'carrier', 'pharmacogenomics', 'nutrition', 'fitness', 'wellness'] as const;
