import { ParsedGenotype, AnalysisResult, MatchedInsight } from './types';
import { KNOWLEDGE_BASE } from './knowledgeBase';

/**
 * Robust parser for 23andMe and MyHeritage raw DNA files.
 * Handles headers, comments, tab or comma delimited, various capitalizations.
 */

export function detectFormat(text: string): '23andMe' | 'MyHeritage' | 'Unknown' {
  const upper = text.slice(0, 4000).toUpperCase();
  if (upper.includes('23ANDME') || upper.includes('THIS FILE WAS GENERATED BY 23ANDME')) return '23andMe';
  if (upper.includes('MYHERITAGE') || upper.includes('MYHERITAGE DNA')) return 'MyHeritage';
  // Heuristic fallback
  if (upper.includes('RSID\TCHROMOSOME') || upper.includes('RSID,CHROMOSOME')) return '23andMe';
  return 'Unknown';
}

export function parseRawDNA(text: string, fileName: string): AnalysisResult {
  const format = detectFormat(text);
  const lines = text.split(/\r?\n/);
  
  const genotypeMap = new Map<string, ParsedGenotype>();
  let delimiter: '\t' | ',' = '\t';
  let headerFound = false;

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    // Try to detect delimiter from first data-like line
    if (!headerFound) {
      if (line.includes('\t') && line.toLowerCase().includes('rsid')) delimiter = '\t';
      else if (line.includes(',') && line.toLowerCase().includes('rsid')) delimiter = ',';
    }

    const parts = line.split(delimiter);
    if (parts.length < 4) continue;

    // Normalize column names
    const col0 = parts[0].trim().toLowerCase();
    if (['rsid', 'rs#', 'rs_id'].includes(col0) && !headerFound) {
      headerFound = true;
      continue;
    }

    // Actual data row
    if (/^rs\d+/i.test(parts[0].trim())) {
      const rsid = parts[0].trim().toLowerCase();
      const genotypeRaw = (parts[3] || '').trim().toUpperCase().replace(/\s/g, '');
      
      // Normalize common missing calls
      const genotype = ['--', '00', '??', ''].includes(genotypeRaw) ? '--' : genotypeRaw;

      if (genotype.length === 2 || genotype === '--') {
        genotypeMap.set(rsid, {
          rsid,
          genotype,
          chromosome: parts[1]?.trim(),
          position: parseInt(parts[2]) || undefined,
        });
      }
    }
  }

  const totalVariantsParsed = genotypeMap.size;

  // Match against our knowledge base
  const insights: MatchedInsight[] = [];
  const categories: Record<string, MatchedInsight[]> = {
    disease_risk: [], carrier: [], pharmacogenomics: [], nutrition: [], fitness: [], wellness: []
  };

  for (const snp of KNOWLEDGE_BASE) {
    const match = genotypeMap.get(snp.rsid.toLowerCase());
    if (match && match.genotype !== '--') {
      const interp = snp.genotypes[match.genotype] || snp.genotypes[match.genotype[0] + match.genotype[1]];
      if (interp) {
        const insight: MatchedInsight = {
          snp,
          genotype: match.genotype,
          interpretation: interp,
        };
        insights.push(insight);
        if (categories[snp.category]) categories[snp.category].push(insight);
      }
    }
  }

  return {
    fileName,
    format,
    totalVariantsParsed,
    matchedVariants: insights.length,
    insights,
    categories: categories as any,
    generatedAt: new Date().toISOString(),
  };
}

// Sample demo datasets (realistic genotypes for demo purposes)
export const DEMO_DATASETS = {
  '23andMe': {
    name: '23andMe Demo',
    format: '23andMe' as const,
    genotypes: {
      'rs429358': 'CT', 'rs7412': 'CC', 'rs4988235': 'GG', 'rs762551': 'AC',
      'rs1815739': 'CT', 'rs9939609': 'AT', 'rs1801133': 'AG', 'rs9923231': 'AG',
      'rs4244285': 'GG', 'rs7903146': 'CT', 'rs10455872': 'AA', 'rs4680': 'AG',
    }
  },
  'MyHeritage': {
    name: 'MyHeritage Demo',
    format: 'MyHeritage' as const,
    genotypes: {
      'rs429358': 'CC', 'rs7412': 'CT', 'rs4988235': 'AA', 'rs762551': 'CC',
      'rs1815739': 'CC', 'rs9939609': 'AA', 'rs1801133': 'GG', 'rs9923231': 'AA',
      'rs4244285': 'AG', 'rs7903146': 'TT', 'rs10455872': 'GG', 'rs4680': 'AA',
    }
  }
};

export function createAnalysisFromDemo(demoKey: keyof typeof DEMO_DATASETS): AnalysisResult {
  const demo = DEMO_DATASETS[demoKey];
  const insights: MatchedInsight[] = [];
  const categories: any = { disease_risk: [], carrier: [], pharmacogenomics: [], nutrition: [], fitness: [], wellness: [] };

  for (const snp of KNOWLEDGE_BASE) {
    const gt = demo.genotypes[snp.rsid];
    if (gt) {
      const interp = snp.genotypes[gt];
      if (interp) {
        const insight = { snp, genotype: gt, interpretation: interp };
        insights.push(insight);
        categories[snp.category].push(insight);
      }
    }
  }

  return {
    fileName: demo.name,
    format: demo.format,
    totalVariantsParsed: Object.keys(demo.genotypes).length * 40, // simulate
    matchedVariants: insights.length,
    insights,
    categories,
    generatedAt: new Date().toISOString(),
  };
}
