import { ParsedGenotype, AnalysisResult, MatchedInsight } from './types';
import { KNOWLEDGE_BASE } from './knowledgeBase';

export function detectFormat(text: string): '23andMe' | 'MyHeritage' | 'Unknown' {
  const upper = text.slice(0, 6000).toUpperCase();
  if (upper.includes('23ANDME') || upper.includes('GENERATED BY 23ANDME')) return '23andMe';
  if (upper.includes('MYHERITAGE') || upper.includes('MYHERITAGE DNA RAW')) return 'MyHeritage';
  if (upper.includes('RSID\T') || upper.includes('RSID,')) return '23andMe';
  return 'Unknown';
}

export function parseRawDNA(text: string, fileName: string): AnalysisResult {
  const format = detectFormat(text);
  const lines = text.split(/\r?\n/);
  const genotypeMap = new Map<string, ParsedGenotype>();
  let delimiter: '\t' | ',' = '\t';
  let headerFound = false;

  for (const rawLine of lines) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    if (!headerFound) {
      if (line.toLowerCase().includes('rsid')) {
        if (line.includes(',')) delimiter = ',';
        headerFound = true;
        continue;
      }
    }

    const parts = line.split(delimiter).map(p => p.trim());
    if (parts.length < 4) continue;

    const rsidCandidate = parts[0].toLowerCase();
    if (/^rs\d{3,}$/.test(rsidCandidate)) {
      let genotype = (parts[3] || '').toUpperCase().replace(/[^ATCGD-]/g, '');
      if (genotype.length > 2) genotype = genotype.slice(0, 2);
      if (['--', '00', '??', ''].includes(genotype)) genotype = '--';

      if (genotype.length === 2 || genotype === '--') {
        genotypeMap.set(rsidCandidate, {
          rsid: rsidCandidate,
          genotype,
          chromosome: parts[1],
          position: parseInt(parts[2]) || undefined
        });
      }
    }
  }

  const totalVariantsParsed = genotypeMap.size;
  const insights: MatchedInsight[] = [];
  const categories: any = { disease_risk: [], carrier: [], pharmacogenomics: [], nutrition: [], fitness: [], wellness: [] };

  for (const snp of KNOWLEDGE_BASE) {
    const match = genotypeMap.get(snp.rsid.toLowerCase());
    if (match && match.genotype !== '--') {
      const g = match.genotype;
      const interp = snp.genotypes[g] || snp.genotypes[g.split('').reverse().join('')]; // handle strand flips sometimes
      if (interp) {
        const insight = { snp, genotype: g, interpretation: interp };
        insights.push(insight);
        categories[snp.category].push(insight);
      }
    }
  }

  return {
    fileName,
    format,
    totalVariantsParsed,
    matchedVariants: insights.length,
    insights,
    categories,
    generatedAt: new Date().toISOString()
  };
}

export const DEMO_DATASETS = { /* ... same as before */ } as const;

export function createAnalysisFromDemo(demoKey: '23andMe' | 'MyHeritage'): AnalysisResult {
  const demo = DEMO_DATASETS[demoKey];
  const insights: MatchedInsight[] = [];
  const categories: any = { disease_risk: [], carrier: [], pharmacogenomics: [], nutrition: [], fitness: [], wellness: [] };

  for (const snp of KNOWLEDGE_BASE) {
    const gt = (demo as any).genotypes[snp.rsid];
    if (gt) {
      const interp = snp.genotypes[gt];
      if (interp) {
        const insight = { snp, genotype: gt, interpretation: interp };
        insights.push(insight);
        categories[snp.category].push(insight);
      }
    }
  }
  return {
    fileName: demo.name,
    format: demo.format,
    totalVariantsParsed: 620000, // realistic
    matchedVariants: insights.length,
    insights,
    categories,
    generatedAt: new Date().toISOString()
  };
}
