import { ParsedGenotype, AnalysisResult, MatchedInsight } from './types';
import { KNOWLEDGE_BASE } from './knowledgeBase';

export function detectFormat(text: string): '23andMe' | 'MyHeritage' | 'AncestryDNA' | 'FamilyTreeDNA' | 'VCF' | 'Unknown' {
  const upper = text.slice(0, 8000).toUpperCase();
  if (upper.includes('23ANDME') || upper.includes('GENERATED BY 23ANDME')) return '23andMe';
  if (upper.includes('MYHERITAGE') || upper.includes('MYHERITAGE DNA RAW')) return 'MyHeritage';
  if (upper.includes('ANCESTRYDNA') || upper.includes('ANCESTRY DNA')) return 'AncestryDNA';
  if (upper.includes('FAMILY TREE DNA') || upper.includes('FAMILYTREEDNA')) return 'FamilyTreeDNA';
  if (upper.includes('##FILEFORMAT=VCF') || /#CHROM\s+POS\s+ID/.test(upper)) return 'VCF';
  if (upper.includes('RSID\T') || upper.includes('RSID,')) return '23andMe';
  return 'Unknown';
}

function parseGenericTSV(text: string): Map<string, ParsedGenotype> {
  const map = new Map<string, ParsedGenotype>();
  const lines = text.split(/\r?\n/);
  let delimiter: '\t' | ',' = '\t';
  let headerFound = false;

  for (const rawLine of lines) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    if (!headerFound && line.toLowerCase().includes('rsid')) {
      if (line.includes(',')) delimiter = ',';
      headerFound = true;
      continue;
    }

    const parts = line.split(delimiter).map(p => p.trim());
    if (parts.length < 4) continue;

    const rsid = parts[0].toLowerCase();
    if (/^rs\d{3,}$/.test(rsid)) {
      let genotype = (parts[3] || '').toUpperCase().replace(/[^ATCGD-]/g, '');
      if (genotype.length > 2) genotype = genotype.slice(0, 2);
      if (['--', '00', '??', ''].includes(genotype)) genotype = '--';
      if (genotype.length === 2 || genotype === '--') {
        map.set(rsid, { rsid, genotype, chromosome: parts[1], position: parseInt(parts[2]) || undefined });
      }
    }
  }
  return map;
}

function parseAncestryDNA(text: string): Map<string, ParsedGenotype> {
  const map = new Map<string, ParsedGenotype>();
  const lines = text.split(/\r?\n/);
  let delimiter = '\t';

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line.toLowerCase().includes('rsid')) {
      if (line.includes(',')) delimiter = ',';
      continue;
    }
    const parts = line.split(delimiter).map(p => p.trim());
    if (parts.length < 5) continue;
    const rsid = parts[0].toLowerCase();
    if (/^rs\d+/.test(rsid)) {
      const g = (parts[3] + parts[4]).toUpperCase().replace(/[^ATCGD-]/g, '');
      const genotype = g.length === 2 ? g : '--';
      if (genotype !== '--') map.set(rsid, { rsid, genotype, chromosome: parts[1], position: parseInt(parts[2]) || undefined });
    }
  }
  return map;
}

function parseVCF(text: string): Map<string, ParsedGenotype> {
  const map = new Map<string, ParsedGenotype>();
  const lines = text.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('##')) continue;
    if (line.startsWith('#CHROM')) continue;

    const parts = line.split(/\t/);
    if (parts.length < 10) continue;

    const id = parts[2];
    if (!id.startsWith('rs')) continue;

    const rsid = id.toLowerCase();
    const ref = parts[3];
    const alt = parts[4].split(',')[0];
    const format = parts[8];
    const sample = parts[9];

    const fmtParts = format.split(':');
    const gtIndex = fmtParts.indexOf('GT');
    if (gtIndex === -1) continue;

    const gtRaw = sample.split(':')[gtIndex] || '';
    const alleles = gtRaw.replace(/[|/]/g, '').slice(0, 2);

    let genotype = '--';
    if (alleles.length === 2) {
      const a1 = alleles[0] === '0' ? ref : alt;
      const a2 = alleles[1] === '0' ? ref : alt;
      genotype = (a1 + a2).toUpperCase();
    }
    if (genotype.length === 2) {
      map.set(rsid, { rsid, genotype, chromosome: parts[0], position: parseInt(parts[1]) || undefined });
    }
  }
  return map;
}

export function parseRawDNA(text: string, fileName: string): AnalysisResult {
  const format = detectFormat(text);
  let genotypeMap: Map<string, ParsedGenotype>;

  if (format === 'AncestryDNA') {
    genotypeMap = parseAncestryDNA(text);
  } else if (format === 'VCF') {
    genotypeMap = parseVCF(text);
  } else {
    genotypeMap = parseGenericTSV(text);
  }

  const totalVariantsParsed = genotypeMap.size;
  const insights: MatchedInsight[] = [];
  const categories: any = { disease_risk: [], carrier: [], pharmacogenomics: [], nutrition: [], fitness: [], wellness: [] };

  for (const snp of KNOWLEDGE_BASE) {
    const match = genotypeMap.get(snp.rsid.toLowerCase());
    if (match && match.genotype !== '--') {
      const g = match.genotype;
      const interp = snp.genotypes[g] || snp.genotypes[g.split('').reverse().join('')];
      if (interp) {
        const insight = { snp, genotype: g, interpretation: interp };
        insights.push(insight);
        categories[snp.category].push(insight);
      }
    }
  }

  return {
    fileName,
    format: format as any,
    totalVariantsParsed,
    matchedVariants: insights.length,
    insights,
    categories,
    generatedAt: new Date().toISOString()
  };
}

export const DEMO_DATASETS = {
  '23andMe': {
    name: '23andMe Demo',
    format: '23andMe' as const,
    genotypes: {
      'rs429358': 'CT', 'rs7412': 'CC', 'rs4988235': 'GG', 'rs762551': 'AC',
      'rs1815739': 'CT', 'rs9939609': 'AT', 'rs1801133': 'AG', 'rs9923231': 'AG',
      'rs4244285': 'GG', 'rs7903146': 'CT', 'rs10455872': 'AA', 'rs4680': 'AG',
    }
  },
  'MyHeritage': {
    name: 'MyHeritage Demo',
    format: 'MyHeritage' as const,
    genotypes: {
      'rs429358': 'CC', 'rs7412': 'CT', 'rs4988235': 'AA', 'rs762551': 'CC',
      'rs1815739': 'CC', 'rs9939609': 'AA', 'rs1801133': 'GG', 'rs9923231': 'AA',
      'rs4244285': 'AG', 'rs7903146': 'TT', 'rs10455872': 'GG', 'rs4680': 'AA',
    }
  }
} as const;

export function createAnalysisFromDemo(demoKey: '23andMe' | 'MyHeritage'): AnalysisResult {
  const demo = DEMO_DATASETS[demoKey];
  const insights: MatchedInsight[] = [];
  const categories: any = { disease_risk: [], carrier: [], pharmacogenomics: [], nutrition: [], fitness: [], wellness: [] };

  for (const snp of KNOWLEDGE_BASE) {
    const gt = (demo as any).genotypes[snp.rsid];
    if (gt) {
      const interp = snp.genotypes[gt];
      if (interp) {
        const insight = { snp, genotype: gt, interpretation: interp };
        insights.push(insight);
        categories[snp.category].push(insight);
      }
    }
  }
  return {
    fileName: demo.name,
    format: demo.format,
    totalVariantsParsed: 620000,
    matchedVariants: insights.length,
    insights,
    categories,
    generatedAt: new Date().toISOString()
  };
}
